DB_NAME: localhost
DB_USERNAME:
DB_PASSWORD:
CMS_MASTER_PASSWORD:
AZURE_STORAGE_ACCOUNT:
AZURE_STORAGE_ACCESS_KEY:
AZURE_CONTAINER_NAME: kitchen1883-development
IMGIX_SOURCE: kitchen1883-development.imgix.net