default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  # database: kitchen1883_development
  database: kitchen1883_development_02

test:
  <<: *default
  database: kitchen1883_test

production:
  <<: *default
  database: kitchen1883_production
  username: kitchen1883
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>